# Generated by Django 4.0.4 on 2022-07-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('pet_type', models.CharField(max_length=30)),
                ('pet_name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('vet_name', models.CharField(max_length=30)),
                ('accepted', models.BooleanField()),
            ],
        ),
    ]
