# Generated by Django 4.0.4 on 2022-07-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='applications',
            name='cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='groom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='house_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='jewelry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='overnight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='walk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='yard_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applications',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
