# Generated by Django 4.0.4 on 2022-08-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_app', '0002_rename_first_name_applications_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom', models.BooleanField(default=False)),
                ('cat', models.BooleanField(default=False)),
                ('walk', models.BooleanField(default=False)),
                ('overnight', models.BooleanField(default=False)),
                ('visit', models.BooleanField(default=False)),
                ('jewelry', models.BooleanField(default=False)),
                ('yard_cleaning', models.BooleanField(default=False)),
                ('house_cleaning', models.BooleanField(default=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('pet_type', models.CharField(max_length=30)),
                ('pet_name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('vet_name', models.CharField(max_length=30)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
